language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - rbx-19mode
gemfile:
  - Gemfile
  - Gemfile.edge
notifications:
  email: false
matrix:
  exclude:
    # Edge Rails is only compatible with 1.9.3+
    - gemfile: Gemfile.edge
      rvm: 1.9.2
  allow_failures:
    - gemfile: Gemfile.edge
      rvm: 1.9.3
    - gemfile: Gemfile.edge
      rvm: ruby-head
    - gemfile: Gemfile.edge
      rvm: rbx-19mode
